# Generated by Django 6.1 on 2026-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='has_room',
            field=models.BooleanField(default=False, help_text='Select this if you already have a room and need a roommate.'),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='room_details',
            field=models.TextField(blank=True, help_text='Optional: room type, rent split, amenities, or other useful details.'),
        ),
    ]
